# Generated by Django 5.0.1 on 2024-02-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_usuario_confirmar_contraseña_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmar_contraseña',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
