# Generated by Django 5.0.1 on 2024-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_usuario_confirmar_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmar_contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=30),
        ),
    ]
