# Generated by Django 5.0.1 on 2024-02-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_rename_productos_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('problematica', models.CharField(max_length=2500)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
