# Generated by Django 5.0.1 on 2024-02-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='problematica',
            field=models.CharField(max_length=200),
        ),
    ]
