# Generated by Django 5.0.1 on 2024-02-21 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_alter_soporte_email_alter_soporte_problematica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
