# Generated by Django 5.0.1 on 2024-02-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_delete_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
