# Generated by Django 5.0.1 on 2024-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('confirmar_contraseña', models.CharField(max_length=255)),
            ],
        ),
    ]
