# Generated by Django 5.0.1 on 2024-02-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicioSesion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
